#!/bin/bash
PASS="youzincrabz"
SCRIPT=$(openssl enc -aes-256-cbc -pbkdf2 -d \
  -in "/root/tunnel.enc" -k "$PASS" 2>/dev/null)
if [[ -z "$SCRIPT" ]]; then
  echo "Error: File rusak!"
  exit 1
fi
exec bash <(echo "$SCRIPT") "$@"
